version: '1.3.0.{build}'
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> src\Our.Umbraco.DataAnnotations\packages.config
before_build:
  - nuget restore src\
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  - provider: GitHub
    release: Our.Umbraco.DataAnnotations-v$(appveyor_build_version)
    description: 'Our.Umbraco.DataAnnotations v$(appveyor_build_version) has been released.'
    auth_token:
      secure: RtBYlXMtdRw5+I8HlXeQxuKUJtoMCjH9inU8Gq6/JUQNB/jSAjhE+W913NR6yHQz
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
  - provider: NuGet
    api_key:
      secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
    tag: 'v$(appveyor_build_version)'
    on:
      branch: master
