version: '1.1.31.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
  - dev-v1
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> **\packages.config
before_build:
  - cmd: nuget restore src\
build:
  verbosity: minimal
after_build:
- cmd: nuget pack src\Our.Umbraco.DataAnnotations\Our.Umbraco.DataAnnotations.csproj
deploy:
  - provider: GitHub
    release: Our.Umbraco.DataAnnotations-v$(appveyor_build_version)
    description: 'Our.Umbraco.DataAnnotations v$(appveyor_build_version) has been released.'
    auth_token:
      secure: RtBYlXMtdRw5+I8HlXeQxuKUJtoMCjH9inU8Gq6/JUQNB/jSAjhE+W913NR6yHQz
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    tag: 'v$(appveyor_build_version)'
    on:
      branch: master                 # release from master branch only

  - provider: NuGet
    api_key:
      secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
    tag: 'v$(appveyor_build_version)'
    on:
      branch: master