version: 1.2.0
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> src\Our.Umbraco.DataAnnotations\packages.config
before_build:
  - nuget restore src\
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  release: Our.Umbraco.DataAnnotations-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
    auth_token:
      secure: RtBYlXMtdRw5+I8HlXeQxuKUJtoMCjH9inU8Gq6/JUQNB/jSAjhE+W913NR6yHQz
    artifact: /.*\.nupkg/          # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only

  - provider: NuGet
    api_key:
      secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

  