version: '1.1.31.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master-v7
  - master-v8
  - dev-v7
  - dev-v8
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> **\packages.config
before_build:
- ps: '& ".\scripts\restore.ps1"'
build:
  verbosity: minimal
before_deploy:
- ps: '& ".\scripts\pack.ps1"'
deploy:
  - provider: GitHub
    release: ralease-$(appveyor_build_version)
    auth_token:
      secure: RtBYlXMtdRw5+I8HlXeQxuKUJtoMCjH9inU8Gq6/JUQNB/jSAjhE+W913NR6yHQz
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    tag: 'release-v$(appveyor_build_version)'
    on:
      branch: /master([-]v[0-9])?/   # release from master branch only

  - provider: NuGet
    api_key:
      secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
    tag: 'release-v$(appveyor_build_version)'
    on:
      branch: /master([-]v[0-9])?/