version: '1.2.2.{build}'
branches:
  only:
  - master-v7
  - master-v8
  - dev-v7
  - dev-v8
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> **\packages.config
before_build:
- ps: '& ".\build\restore.ps1"'
build:
  verbosity: minimal
after_build:
- ps: '& ".\build\pack.ps1"'
deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: RtBYlXMtdRw5+I8HlXeQxuKUJtoMCjH9inU8Gq6/JUQNB/jSAjhE+W913NR6yHQz
    artifact: /.*/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    tag: $(APPVEYOR_REPO_TAG_NAME)
    on:
      branch: /master([-]v[0-9])?/   # release from master branch only
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
    on:
      branch: /master([-]v[0-9])?/
      APPVEYOR_REPO_TAG: true