version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore src\
build:
  publish_nuget: true
  verbosity: minimal
after_build:
  - nuget pack src\Our.Umbraco.DataAnnotations\Our.Umbraco.DataAnnotations.csproj
deploy:
- provider: NuGet
  api_key:
    secure: xrveHCc8uVCO8671TOphpNnJpiYEhZzmc8AZjv5qnvt5GqPsCDOgddYednb7EM7M
  on:
    branch: master
cache:
  - packages -> src\Our.Umbraco.DataAnnotations\packages.config