# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master-v8
- dev-v8

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Download nuget installer'

- task: NuGetCommand@2
  displayName: 'Restore solution'
  inputs:
    restoreSolution: '$(solution)'

- task: YarnInstaller@3
  displayName: 'Download yarn installer'
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: 'Run yarn'
  inputs:
    projectDirectory: 'build'

- task: Grunt@0
  displayName: 'Run grunt publish task'
  inputs:
    gruntFile: 'build/gruntfile.js'
    targets:
    gruntCli: 'node_modules/grunt-cli/bin/grunt'

- task: CopyFiles@2
  displayName: 'Copy files to staging directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'build/$(BuildConfiguration)/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish staging directory to artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop